# Generated by Django 5.1.1 on 2024-12-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datlich', '0006_usermodel_is_active_usermodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
