# Generated by Django 5.1.1 on 2024-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datlich', '0010_alter_usermodel_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
