# Generated by Django 5.1.1 on 2024-12-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datlich', '0012_usermodel_is_staff_alter_usermodel_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
